version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "python wait_for_db.py &&
      uvicorn src.main:app --host 0.0.0.0 --port 8080"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrations:
    build: .
    env_file:
      - .env
    command: >
      sh -c "python wait_for_db.py &&
      alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: